FROM sparkpos/docker-nginx-php:latest

#Install Newrelic
RUN set -x && DEBIAN_FRONTEND=noninteractive \
  && wget -O - https://download.newrelic.com/548C16BF.gpg | apt-key add - \
  && echo "deb http://apt.newrelic.com/debian/ newrelic non-free" > /etc/apt/sources.list.d/newrelic.list \
  && apt-get update \
  && apt-get install -y newrelic-php5 \
  && newrelic-install install \
  && unlink /etc/php/7.1/fpm/conf.d/20-newrelic.ini \
  && unlink /etc/php/7.1/cli/conf.d/20-newrelic.ini \
  && rm -rf /var/lib/apt/lists/*

RUN export NR_INSTALL_SILENT=true && \
    sed -i "s/newrelic.appname = .*/newrelic.appname = \"$NEWRELICAPPNAME\"/" /etc/php/7.1/fpm/conf.d/newrelic.ini && \
    sed -i "s/newrelic.license = .*/newrelic.license = \"$NEWRELICKEY\"/" /etc/php/7.1/fpm/conf.d/newrelic.ini
